name: 'salesman_dart'
version: 0.0.3
description: Solving a TSP using Dart.
#author: Your Name <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  #polymer_elements: "^0.3.0"
  core_elements: "^0.7.1+6"
  paper_elements: "^0.7.1+2"
  polymer: "^0.16.4+1"
  web_components: "^0.12.0"
  reflectable: "^0.5.2"
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter
- polymer:
    entry_points: 
    - web/index.html
    - web/text_reverser.html